enum COMMON {
  "ENTITIES_UPDATE" = "COMMON/ENTITIES_UPDATE",
  "PAGE_STATE_LOAD" = "COMMON/PAGE_STATE_LOAD",
  "PAGE_STATE_LOAD_FAILED" = "COMMON/PAGE_STATE_LOAD_FAILED"
}

enum PROJECTS {
  INIT = "PROJECTS/INIT"
}

export { COMMON, PROJECTS };
